repos:
  # - repo: local
  #   hooks:
  #     - id: export-req
  #       name: export requirements
  #       language: system
  #       pass_filenames: false
  #       entry: bash -c "poetry export -f requirements.txt --without-hashes  | awk '{ print $1 }' FS=';' > prefect/requirements.txt"
  #       files: ^(pyproject.toml|poetry.lock)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
