repos:
  # - repo: local
  #   hooks:
  #     - id: export-req
  #       name: export requirements
  #       language: system
  #       pass_filenames: false
  #       entry: bash -c "poetry export -f requirements.txt --without-hashes  | awk '{ print $1 }' FS=';' > prefect/requirements.txt"
  #       files: ^(pyproject.toml|poetry.lock)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0 # pick a git hash / tag to point to
    hooks:
      - id: flake8
        entry: flake8p
        args: ["--toml-config", "./pyproject.toml"]
        additional_dependencies: [Flake8-pyproject]
