---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
  labels:
    name: minio-operator
    purpose: bucket-storage
spec:
  destination:
    name: "{{.Values.spec.destination.name}}"
    namespace: minio-operator
  project: "{{.Values.spec.project}}"
  source:
    repoURL: 'https://operator.min.io'
    targetRevision: 5.0.15
    chart: operator
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
          hosts:
            - minio.localhost
        consoleIngress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
          hosts:
            - minio.localhost
          path: /console
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
