---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: minio-operator
  labels:
    name: minio-operator
spec:
  destination:
    name: "{{ .Values.spec.destination.name }}"
    namespace: minio-operator
  project: "{{ .Values.spec.project }}"
  source:
    path: gitops/workloads/minio-operator
    repoURL: "{{.Values.spec.source.repoURL}}"
    targetRevision: "{{.Values.spec.source.targetRevision}}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
