---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    name: traefik
    purpose: network-components
spec:
  destination:
    name: "{{.Values.spec.destination.name}}"
    namespace: traefik
  project: "{{.Values.spec.project}}"
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: 28.3.0
    chart: traefik
    helm:
      values: |
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            entryPoints:
              - web
              - traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
