---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress-controller
  namespace: argocd
  labels:
    name: traefik-ingress-controller
    purpose: network-components
spec:
  destination:
    name: "{{.Values.spec.destination.name}}"
    namespace: traefik
  project: "{{.Values.spec.project}}"
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: 28.3.0
    chart: traefik
    helm:
      values: |
        dashboard:
          enable: true
          ingressROute: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
