applications:
- name: mlops-presentation
  namespace: argocd
  project: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  sources:
  - repoURL: git@github.com:${gh_username}/mlops-presentation.git
    path: gitops/cluster
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  revisionHistoryLimit: null
