# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

global:
  logging:
    format: json

configs:
  repositories:
    traefik:
      url: https://traefik.github.io/charts
      name: traefik
      type: helm
    minio-operator:
      url: https://operator.min.io
      name: minio-operator
      type: helm
  cm:
    configManagementPlugins: |
      - name: kustomize-enable-helm
        generate:
          command: [ "sh", "-c" ]
          args: [ "kustomize build --enable-helm" ]

  params:
    server.insecure: true
